const tintColor = "#00fff0"

export default {
  primary: "#314bfc",
  primaryDarker: "#3d00cc",
  cyan: "#80FFF7",
  textOnPrimary: "#fff",
  white: "#fff",
  mainBackground: "#f3f0e7",
  text: "#1c1a13",
  textMuted: "#89836b",
  danger: "red",
  success: "#85D900",
  tintColor,
  tabIconDefault: "#ccc",
  tabIconSelected: tintColor,
  tabBar: "#fefefe",
  errorBackground: "red",
  errorText: "#fff",
  warningBackground: "#EAEB5E",
  warningText: "#666804",
  noticeBackground: tintColor,
  noticeText: "#fff",
  shadow: "#bdb9a9",
  insetShadow: "#89836b",
}
